title: Emilia Buckley
description: Hi, I’m Emilia Buckley, and this is my Web site!
url: https://emilia.buckley.name

exclude:
  - CNAME
  - Gemfile
  - vendor

social:
  linkedin:
    type: fab
    text: LinkedIn
    url: https://www.linkedin.com/in/emiliabuckley
  user-graduate:
    text: CV
    url: /cv.pdf
