title: Emilia Buckley
description: Hi, I’m Emilia Buckley, and this is my Web site!
url: https://emilia.buckley.name

exclude:
  - CNAME
  - Gemfile
  - vendor

social:
  linkedin:
    type: fab
    text: LinkedIn
    url: https://www.linkedin.com/in/emiliabuckley
  user-graduate:
    text: CV
    url: https://docs.google.com/document/d/1rFWAqZL5bflf41XSFfoArD9quuI2CLBatLxXhKN7I_o/export?format=pdf
