title: Emilia Buckley
description: Hi, I’m Emilia Buckley, and this is my Web site!
url: https://emilia.buckley.name

exclude:
  - CNAME
  - Gemfile
  - vendor

social:
  linkedin:
    text: Emilia Buckley on LinkedIn
    url: https://www.linkedin.com/in/emiliabuckley
  profile:
    text: Emilia Buckley’s CV
    url: /cv.pdf
